name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build Backend Docker Image
        run: docker build ./backend --file ./backend/Dockerfile --tag ppquickwork/backend-image:latest

      - name: Build Frontend Docker Image
        run: docker build ./frontend --file ./frontend/Dockerfile --tag ppquickwork/frontend-image:latest

      - name: Push Backend Image to Docker Hub
        run: docker push ppquickwork/backend-image:latest

      - name: Push Frontend Image to Docker Hub
        run: docker push ppquickwork/frontend-image:latest
