name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for backend
      run: docker build ./backend --file backend/Dockerfile --tag my-backend-image:$(date +%s)

    - name: Build the Docker image for frontend
      run: docker build ./frontend --file frontend/Dockerfile --tag my-frontend-image:$(date +%s)

